apiVersion: v1
kind: Pod
metadata:
  name: dogs-pod
  labels:
    app.kubernetes.io/name: dogs
    app.kubernetes.io/app: dogs
  namespace: dogs
spec:
  containers:
  - image: 199999432832.dkr.ecr.us-east-1.amazonaws.com/dogs-image:v7
    name: dogs-container
    ports:
    - containerPort: 80