apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cats-replica
  labels:
    app.kubernetes.io/name: cats
    app.kubernetes.io/app: cats
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cats
      app.kubernetes.io/app: cats
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cats
        app.kubernetes.io/app: cats
    spec:
      containers:
      - image: 199999432832.dkr.ecr.us-east-1.amazonaws.com/cats-image:v20
        name: cats
        ports:
        - containerPort: 80