apiVersion: v1
kind: Service
metadata:
  name: dogs
  labels:
    app.kubernetes.io/name: dogs
    app.kubernetes.io/app: dogs
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30001
  selector:
    app.kubernetes.io/name: dogs
    app.kubernetes.io/app: dogs