apiVersion: v1
kind: Service
metadata:
  name: cats
  labels:
    app.kubernetes.io/name: cats
    app.kubernetes.io/app: cats
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30000
  selector:
    app.kubernetes.io/name: cats
    app.kubernetes.io/app: cats